[project]
name = "utils"
version = "0.1.0"
description = "Utility helpers that build on acme-core"
readme = "README.md"
authors = [
    { name = "Michael Ekwueme", email = "ekwuemem@uci.edu" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
utils = "utils:main"

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"
